package de.compament.backendrestapi.competition.material;

public enum MatchType {
    GROUP_MATCH, SECOND_ROUND, THIRD_ROUND, FOURTH_ROUND, FIFTH_ROUND, SIXTH_ROUND, SEVENTH_ROUND, EIGHTH_ROUND, NINTH_ROUND, TENTH_ROUND,
    ROUND_OF_64, ROUND_OF_32, ROUND_OF_16, QUARTER_FINAL, SEMI_FINAL, FINAL
}
